name: Tests

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  nodejs-fairos:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install fdp-play
        run: npm install -g @fairdatasociety/fdp-play
      - name: Run fdp-play
        run: fdp-play start --detach
      - name: Download fairos
        run: wget https://github.com/fairDataSociety/fairOS-dfs/releases/download/v0.8.2-rc6/dfs_v0.8.2-rc6_linux_amd64
      - name: Install fairos
        run: \
            && mv dfs_v0.8.2-rc6_linux_amd64 dfs \
            && chmod +x dfs \
            && ./dfs version